print ("Hello RJ")
print ("Hello UFF")
print ("Hello Uff")
print ("Hello Brasil")
print ("Hello IC")
print ("Hello Predio 2")
print ("Hello A")
print ("Hello B")
print ("Hello C")
print ("Hello D")
print ("Hello E")
print ("Hello F") 
print ("Hello G")
print ("Hello Predio 1")
print ("Hello RJ")
